In [1]:
import torch 

### dim使用方法

In [2]:
a = torch.Tensor([[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]])
b = torch.Tensor([[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]])
a.shape

torch.Size([1, 4, 4])

In [6]:
a = torch.Tensor([[1,2,3,4] ,
    [5,6,7,8]])
a.shape[0]


2

In [8]:
s = torch.sum(a , dim=1)
s

tensor([10., 26.])

### cat

In [16]:
A = torch.ones(2,2)
B = torch.rand(2,3)
torch.cat((A , B ) ,dim = 1)

tensor([[1.0000, 1.0000, 0.9013, 0.7567, 0.9555],
        [1.0000, 1.0000, 0.0697, 0.9187, 0.6566]])

### unsqueeze
自动去除1的向量值

In [23]:
c = torch.tensor([[[1., 2., 4.],
        [4., 5., 7.],
        [3., 9., 8.],
        [9., 6., 7.]] ,
        [[1., 2., 4.],
        [4., 5., 7.],
        [3., 9., 8.],
        [9., 6., 7.]]])
c.shape

torch.Size([2, 4, 3])

In [30]:
d = torch.tensor([[[1., 2., 4.],
        [4., 5., 7.],
        [3., 9., 8.],
        [9., 6., 7.]]])
d.shape

torch.Size([1, 4, 3])

In [31]:
b = c.squeeze(0)
b.shape
e = d.squeeze(0)
e.shape

torch.Size([4, 3])

### Tensorset

In [33]:
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

a = torch.Tensor([[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]])
b = torch.Tensor([[[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]])
dataset = TensorDataset(a , b)
dataloader = DataLoader(dataset , batch_size=2 , shuffle=True)
for x , y in dataloader:
    print(x.shape)
    print(y.shape)
    break
dataset

torch.Size([1, 4, 4])
torch.Size([1, 4, 4])


In [38]:
# 基本用法
import torch
from torch.utils.data import TensorDataset, DataLoader

# 创建 TensorDataset
x = torch.randn(100, 10)  # 100个样本，每个样本10个特征
y = torch.randint(0, 2, (100,))  # 100个标签

dataset = TensorDataset(x, y)  # 将特征和标签组合

# 使用 DataLoader 加载数据
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)
print(x[:5,:])
print(y)
# 遍历数据
for batch_x, batch_y in dataloader:
    print(batch_x.shape, batch_y.shape)

tensor([[-0.9430,  0.8002, -0.1742, -0.0616, -0.9550,  0.2951, -1.0719, -0.2283,
          0.5249,  0.4522],
        [-0.2087,  1.2640, -0.5390,  1.3979, -1.0033,  0.0926, -0.3388, -0.0264,
          0.1840, -0.7783],
        [-1.3138, -1.8671,  0.2491, -0.7830, -1.3176,  0.8056,  0.4848,  1.2810,
          0.3598, -0.6816],
        [ 1.5271,  1.2267,  2.0211,  1.3603, -1.1532,  0.9098, -0.0607, -0.6168,
         -0.1043, -0.3228],
        [-0.1886,  1.0234,  0.0612,  1.2426,  0.7925, -0.1919, -0.3099,  0.7824,
          1.2561,  0.7802]])
tensor([0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 1, 1])
torch.Size([32, 10]) torch.Size([32])
torch.Size([32, 10]) torch.Size([32])
torch.Size([32, 10]) torch.Size([32])

In [ ]:
dataloaderTwo = DataLoader(dataset , batch_size=2 , shuffle=True)
for i , data in enumerate(dataloaderTwo):
    print(i)
    print(data[0].shape)

In [42]:
from torch.utils.data import Dataset
class subDataset(Dataset):
    # 初始化
    def __init__(self , Data , Label):
        self.Data = Data
        self.Label = Label
    # 返回数据集的大小
    def __len__(self):
        return len(self.Data)
    # 得到数据内容和标签
    def __getitem__(self , index):
        data = torch.Tensor(self.Data[index])
        label = torch.Tensor(self.Label[index])
        return data , label 

In [49]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader

# 1. 生成随机数据
X = np.random.rand(100, 10)     # 100个样本，每个样本10个特征
y = np.random.randint(0, 2, 100)  # 100个二分类标签

# 2. 创建自定义数据集
class subDataset(Dataset):
    def __init__(self, Data, Label):
        self.Data = torch.FloatTensor(Data)   # 转换为 FloatTensor
        self.Label = torch.LongTensor(Label)  # 转换为 LongTensor

    def __len__(self):
        return len(self.Data)

    def __getitem__(self, index):
        return self.Data[index], self.Label[index]

# 3. 实例化数据集
dataset = subDataset(X, y)

# 4. 创建 DataLoader
dataloader = DataLoader(
    dataset, 
    batch_size=2,   # 每批次2个样本
    shuffle=True    # 随机打乱数据
)

# 5. 遍历数据
for i, (batch_data, batch_labels) in enumerate(dataloader):
    print('Batch Data Shape:', batch_data.shape)
    print('Batch Label Shape:', batch_labels.shape)
    break  # 只打印第一个批次

# 6. 访问单个样本
single_data, single_label = dataset[0]
print("Single Data: {} and Single Label: {}".format(single_data, single_label))

Batch Data Shape: torch.Size([2, 10])
Batch Label Shape: torch.Size([2])
Single Data: tensor([0.2061, 0.4720, 0.7913, 0.7656, 0.1922, 0.1079, 0.3168, 0.6801, 0.7886,
        0.2130]) and Single Label: 1


### 矩阵乘法

In [53]:
a = torch.rand(2,3)
b = torch.rand(3,4)
# 将b展开成一阶张量
b.view(-1)

tensor([0.5010, 0.2619, 0.3202, 0.9386, 0.4991, 0.5295, 0.3151, 0.4762, 0.4499,
        0.6920, 0.6998, 0.2091])

In [55]:
c = torch.matmul(a,b)
c.T

tensor([[0.8536, 1.3161],
        [0.9215, 1.3676],
        [0.8655, 1.2263],
        [0.9017, 1.4428]])